module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = { exports: {} }; __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); if(typeof m.exports === "object") { __MODS__[modId].m.exports.__proto__ = m.exports.__proto__; Object.keys(m.exports).forEach(function(k) { __MODS__[modId].m.exports[k] = m.exports[k]; var desp = Object.getOwnPropertyDescriptor(m.exports, k); if(desp && desp.configurable) Object.defineProperty(m.exports, k, { set: function(val) { __MODS__[modId].m.exports[k] = val; }, get: function() { return __MODS__[modId].m.exports[k]; } }); }); if(m.exports.__esModule) Object.defineProperty(__MODS__[modId].m.exports, "__esModule", { value: true }); } else { __MODS__[modId].m.exports = m.exports; } } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1574769826130, function(require, module, exports) {
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports):"function"==typeof define&&define.amd?define(["exports"],t):t((e=e||self)["micro-reaction"]={})}(this,function(e){var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},i=new WeakMap,u=new WeakMap,a=[];function y(){var e,t,n=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};return u.get(n)||(e=n,t=new Proxy(e,{get:function(e,t,n){var o=Reflect.get(e,t,n);!function(e){var t=e.target,n=e.key,o=a[a.length-1];if(o){var r=i.get(t);r.get(n)||r.set(n,o)}}({target:e,key:t});var r=u.get(o);return"object"===(void 0===o?"undefined":f(o))&&null!=o&&0<a.length?y(o):r||o},set:function(e,t,n,o){var r=Reflect.set(e,t,n,o);return function(e){var t=e.target,n=e.key,o=i.get(t);if(o.has(n)){var r=o.get(n);r()}}({target:e,key:t}),r}}),i.set(e,new Map),u.set(e,t),t)}e.observable=y,e.observe=function(e){if(-1===a.indexOf(e))try{a.push(e),Reflect.apply(e,this,arguments)}finally{a.pop()}},Object.defineProperty(e,"__esModule",{value:!0})});

}, function(modId) {var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1574769826130);
})()
//# sourceMappingURL=index.js.map